#!/usr/bin/env bash
# Configure the web-02 to be identical to web-01
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html /var/www/error
sudo chmod -R 755 /var/www

echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

hostname=$(hostname)
server_config=$(cat <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
        add_header X-Served-By \$hostname;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF
)

echo "$server_config" | sudo tee /etc/nginx/sites-enabled/default

sudo service nginx restart
