#!/usr/bin/env bash
# Install and configure HAproxy on my lb-01 server

sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get install haproxy=2.6.\*
sudo cp -a /etc/haproxy/haproxy.cfg{,.original_copy}
sudo echo "
frontend froches_front
        bind 127.0.0.1:80
        default_backend froches_servers

backend froches_servers
        balance roundrobin
        server web-01 52.91.120.5:80 check
        server web-02 54.237.33.167:80 check
" > /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
