#!/usr/bin/env bash
# Install and configure HAproxy on my lb-01 server

sudo apt -y upgrade
sudo apt -y update
sudo apt -y install haproxy
echo "
frontend froches_front
	mode http
        bind *:80
        default_backend froches_servers

backend froches_servers
	mode http
        balance roundrobin
        server 330540-web-01 52.91.120.5:80 check
        server 330540-web-02 54.237.33.167:80 check
" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy restart
