#!/usr/bin/env bash
# Comment... Will add later
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 71770-web-01 100.24.206.107:80 check\n\tserver 71770-web-02 100.25.131.225:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
