#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it.

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 <mysql_root_password>"
	exit 1
fi

mysql_root_password="$1"

time=$(date +%d-%m-%Y)

destination="backup.sql"
archive_name="{time}.tar.gz"

sudo mysqldump -u root -p "${mysql_root_password}" --all-databases | gzip > "${archive_name}"

if [ $? -ne 0 ]; then
	echo "Error: MySQL dump failed."
	exit 1
fi

echo "Backup completed successfully. Archive: ${archive_name}"
