#!/usr/bin/env bash
# Script that: Creates the file /var/run/myscript.pid containing its PI
#+ Displays To infinity and beyond indefinitel
#+ Displays I hate the kill command when receiving a SIGTERM signa
#+ Displays Y U no love me?! when receiving a SIGINT signa
#+ Deletes the file /var/run/myscript.pi
#+ and terminates itself when receiving a SIGQUIT or SIGTERM signa

terminator() {
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	trap 'terminator' SIGQUIT
done
