#!/usr/bin/env bash
# Configuring ufw
sudo apt-get update -y
sudo apt-get install nginx ufw -y
sudo ufw allow ssh
sudo ufw allow 'Nginx Full'
sudo ufw enable
sudo ufw status numbered
rm /etc/nginx/sites-enabled/default
sudo systemctl reload nginx
